In [6]:
import pandas as pd
import numpy as np





# DECISION TREE ,BAGGING ,BOOSTING

In [7]:
cars_data=pd.read_csv(r'C:\Users\hp\Desktop\cars.csv', header=None)
cars_data.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [8]:
cars_data.shape

(1728, 7)

In [9]:
cars_data.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
cars_data.head()

buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

In [10]:
cars_data.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [11]:
cars_df=pd.DataFrame.copy(cars_data)

In [12]:
colname=cars_df.columns[:]
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [15]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for x in colname:
    cars_df[x]=le.fit_transform(cars_df[x])

In [16]:
colname=cars_df.columns[:]
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [17]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

scaler.fit(X)
X=scaler.transform(X)

print(X)

[[ 1.34164079  1.34164079 -1.34164079 -1.22474487  1.22474487  0.        ]
 [ 1.34164079  1.34164079 -1.34164079 -1.22474487  1.22474487  1.22474487]
 [ 1.34164079  1.34164079 -1.34164079 -1.22474487  1.22474487 -1.22474487]
 ...
 [-0.4472136  -0.4472136   1.34164079  1.22474487 -1.22474487  0.        ]
 [-0.4472136  -0.4472136   1.34164079  1.22474487 -1.22474487  1.22474487]
 [-0.4472136  -0.4472136   1.34164079  1.22474487 -1.22474487 -1.22474487]]


C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

In [36]:
#from sklearn.tree import DecisionTreeClassifier
#model_DecisionTree=DecisionTreeClassifier(random_state=10,min_samples_leaf=3,max_depth=10,criterion='entropy')
#model_DecisionTree.fit(X_train,Y_train)
#Y_pred=model_DecisionTree.predict(X_test)

#from sklearn.ensemble import ExtraTreesClassifier
#model=(ExtraTreesClassifier(50,random_state=10))             #BAGGING APPROACHES   #change of hyperparameters
#modelmodel.fit(X_train,Y_train)
#Y_pred=model.predict(X_test)

#from sklearn.ensemble import RandomForestClassifier
#model_RandomForest=RandomForestClassifier(100,random_state=10)
#model_RandomForest.fit(X_train,Y_train)
#Y_pred=model_RandomForest.predict(X_test)

In [42]:
#from sklearn.ensemble import AdaBoostClassifier
#model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(),random_state=10)
#model_AdaBoost.fit(X_train,Y_train)
#Y_pred=model_AdaBoost.predict(X_test)
                                                               #BOOSTING APPROACHES  
                                                               
#from sklearn.ensemble import GradientBoostingClassifier
#model_GradientBoosting=GradientBoostingClassifier(n_estimators=200,random_state=10)
#model_GradientBoosting.fit(X_train,Y_train)
#Y_pred=model_GradientBoosting.predict(X_test)


In [37]:
Y_pred=model_DecisionTree.predict(X_test)

print(list(zip(Y_test,Y_pred)))

[(2, 2), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (1, 1), (3, 3), (1, 1), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (3, 0), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (3, 0), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (3, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 1), (2, 2), (2, 2), (1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 1),

In [38]:
from sklearn.metrics import confusion_matrix,accuracy_score,\
classification_report
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)

print("accuracy of the model:",acc)

[[ 97   3   2   0]
 [  4  17   0   0]
 [  6   0 365   0]
 [  4   1   0  20]]
classification report:
              precision    recall  f1-score   support

           0       0.87      0.95      0.91       102
           1       0.81      0.81      0.81        21
           2       0.99      0.98      0.99       371
           3       1.00      0.80      0.89        25

   micro avg       0.96      0.96      0.96       519
   macro avg       0.92      0.89      0.90       519
weighted avg       0.96      0.96      0.96       519

accuracy of the model: 0.9614643545279383


In [39]:
print(list(zip(colname,model_DecisionTree.feature_importances_)))

[('buying', 0.17152489685401104), ('maint', 0.22240770169696275), ('doors', 0.04716153193906964), ('persons', 0.20324127591217964), ('lug_boot', 0.09821266332378895), ('safety', 0.257451930273988)]


In [33]:
from sklearn import tree
with open("model_DecisionTree.txt","w")as f:
    f=tree.export_graphviz(model_DecisionTree, feature_names=colname[:-1],out_file=f)

#generate the file and upload the code in webgraphviz.com to plot the decision tree